title: 42 Labs

theme: minima

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/devansh42" }
    - { platform: youtube, user_url: "https://youtube.com/theshareefcoder" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/devansh42" }

google_analytics: G-44RLQ7MWVX

